version: "3.8"
# https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  nginx:
    image: nginx:alpine
    # https://hub.docker.com/_/nginx
    networks:
      - inventree
    volumes:
      - static:/var/www/inventree/static
      - media:/var/www/inventree/media
    ports:
      # CHANGE TO 80:80 IF USING NGINX FOR SSL TERMINATION
      - 9080:80
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - 443:443
    configs:
      - source: inventree_nginx.conf
        target: /etc/nginx/templates/nginx.conf.template
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      # https://nginx.org/en/docs/ngx_core_module.html#worker_processes
      - NGINX_WORKER_PROCESSES=auto
      # https://nginx.org/en/docs/ngx_core_module.html#worker_rlimit_nofile
      - NGINX_WORKER_RLIMIT_NOFILE=65535
      # https://nginx.org/en/docs/ngx_core_module.html#worker_connections
      - NGINX_WORKER_CONNECTIONS=65535
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
      - NGINX_CLIENT_MAX_BODY_SIZE=10m
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_timeout
      - NGINX_CLIENT_BODY_TIMEOUT=30s
      - NGINX_HOST=inventree.yourdomain.test
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - NGINX_SSL_CERT=yourdomain.test.crt
      # - NGINX_SSL_KEY=yourdomain.test.key
    # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
    # secrets:
    #   - source: yourdomain.test.crt
    #     target: /etc/nginx/certs/yourdomain.test.crt
    #   - source: yourdomain.test.key
    #     target: /etc/nginx/certs/yourdomain.test.key

  mariadb:
    image: mariadb:latest
    # https://hub.docker.com/_/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/inventreesql_root_password
      - MYSQL_DATABASE=inventree
      - MYSQL_USER=inventree
      - MYSQL_PASSWORD_FILE=/run/secrets/inventreesql_password
    secrets:
      - inventreesql_root_password
      - inventreesql_password
    networks:
      - mariadb

  inventree:
    image: zeigren/inventree:0.2.2
    # https://hub.docker.com/r/zeigren/inventree
    networks:
      - inventree
      - mariadb
    volumes:
      - static:/usr/src/static
      - media:/usr/src/media
    environment:
      - DATABASE_PASSWORD=DOCKER-SECRET->inventreesql_password
      - DATABASE_NAME=inventree
      - DATABASE_USER=inventree
      #- GUNICORN_WORKERS=2
      # CREATE SUPERUSER ONCE THEN DELETE THESE
      - CREATE_SUPERUSER=False
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
      - DJANGO_SUPERUSER_PASSWORD=admin
    secrets:
      - inventreesql_password

networks:
  inventree:
  mariadb:

volumes:
  static:
  media:
  mariadb:

secrets:
  inventreesql_root_password:
    external: true
  inventreesql_password:
    external: true
  # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
  # yourdomain.test.crt:
  #   external: true
  # yourdomain.test.key:
  #   external: true

configs:
  inventree_nginx.conf:
    external: true
