version: '3.7'
services:
  nginx:
    volumes:
      - ./config/inventree_dev_vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9080:80"

  inventree:
    image: zeigren/inventree:latest
    environment:
      - DEBUG=False
