#!/bin/bash

INVENTREE_MASTER_COMMIT=$(git ls-remote https://github.com/inventree/InvenTree.git master)
COMMIT_STUB=$(echo $INVENTREE_MASTER_COMMIT | cut -c1-7)
INVENTREE_TAG=$(git tag --sort=-version:refname | head -n 1)

echo "[***] Adding labels"

if $DOCKER_TAG == latest ; then
docker tag $IMAGE_NAME $DOCKER_REPO:$INVENTREE_TAG-$COMMIT_STUB
docker push $DOCKER_REPO:$INVENTREE_TAG-$COMMIT_STUB ; fi
